INSERT INTO activities(name, phone, website_url, address, description, image_url, city_id, category_id)
VALUES
('FOUQUET''S', '+33(0)1 40 69 60 50', 'https://www.hotelsbarriere.com/fr/paris/le-fouquets/restaurants-et-bars/fouquets.html',  '99, avenue des Champs-Elysées, 75 008 Paris, France', 'Since 1899, Fouquet''s brasserie has embodied the Parisian spirit, brilliant and festive. Ideally located at the corner of the Champs-Elysées and Avenue George V, the famous brasserie houses a classic Parisian brasserie decor, and proudly displays its eternal link with the arts and cinema. This mythical setting opens onto two magnificent terraces, on the Champs-Elysées and Avenue George V.', 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/f2fa383d-eee5-452f-80c4-af21fb6d433a/714dfd3d-6b3b-418d-803e-d40a442d0339.jpg', 1, 1),
('Le Jules Verne', '+33(0)1 83 77 34 34', 'https://www.restaurants-toureiffel.com/en/jules-verne-restaurant.html', '2nd floor of the Eiffel Tower, Avenue Gustave Eiffel, 75007 Paris, France', 'Le Jules Verne is a dizzying ascent of the Eiffel Tower to enjoy the most beautiful view of Paris. Three dining rooms give three exceptional viewpoints: Quai Branly, Trocadéro and Champ de Mars.', 'https://bonjourparis.com/wp-content/uploads/2020/02/Interiors-LJV_Trocadero_02_Copyright-Marie-Line-Sina-min-min.jpg', 1, 1),
('Jòia', '+33(0)1 40 20 06 06', 'https://www.joiahelenedarroze.com/en/', '39 rue des Jeuneurs, 75002 Paris,France', 'On two floors, Joia boasts a casual and warm elegance. On the plate, grandmothers'' recipes are combined with London, New York and Italian-inspired delicacies. A few friends crush their own guacamole in a mortar while waiting for the next step, while two lovers enjoy a cogote of hake from Saint-Jean de Luz, roasted in a Spanish style with a chimichurri sauce.', 'https://www.joiahelenedarroze.com/_files/_media/27/Photos/Helene-Darroze-Joia.jpg', 1, 1),
('Aux Bons Crus', '+33(0)1 45 67 21 13', 'http://www.auxbonscrus.fr/index_en.html', '54 rue Godefroy Cavaignac, 5011 Paris, France', 'Welcome to Aux Bons Crus, the true Parisian Bistro, the one you dreamt of. Sit down, relax and enjoy our family recipes from the region of Lyon, the land of famous chef Paul Bocuse! The menu offers simple yet delicious dishes made with fresh ingredients, every day.', 'http://www.auxbonscrus.fr/img2/IMG_4157.jpg', 1, 1),
('Le Mur Des Je t''aime (The Wall of Love)', null, 'http://www.lesjetaime.com/', 'Square Jehan Rictus, Place des Abbesses, 75018 Paris, France', 'Tucked away in Montmartre’s petite Jehan Rictus garden square, Le Mur Des Je t’aime attracts its fair share of lovebirds each day. Artists Fédéric Baron and Claire Kito created the mural in 2000, adorning it with hundreds of variations of Je t’aime (I Love You) in 250 different languages and dialects.', 'https://lh3.googleusercontent.com/proxy/-NGkiJ0fML5MYSDHryb5rPceTwW5qtAqTChekMuIIYsAw7D3Xy74jLCK2adG4Da6n1i42usTaIM5XysKbI1h50xljJNxOrPf62VK3dWOMM4Ysw_7CAbypqylhfm7Qu8V-UJruI-SlcQ0-6ACyFrV3U3KzxiM', 1, 4),
('La Tour Eiffel (The Eiffel Tower)', '+33 (0)8 92 70 12 39', 'https://www.toureiffel.paris/en', 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France', 'The Eiffel Tower, La Tour Eiffel in French, was the main exhibit of the Paris Exposition — or World''s Fair — of 1889. It was constructed to commemorate the centennial of the French Revolution and to demonstrate France''s industrial prowess to the world.', 'https://cdn.mos.cms.futurecdn.net/z3rNHS9Y6PV6vbhH8w83Yn-1024-80.jpg.webp', 1, 4),
('Chàteau de Versailles (Palace of Versailles', '+ 33(0)1 30 83 78 00', 'http://en.chateauversailles.fr/', 'Place d''Armes, 78000 Versailles, France', 'About an hour outside of the city, Palace de Versailles—once the home of infamous Marie Antoinette—is a day trip worth making. Wander through the chandelier-strung Hall of Mirrors, the King’s seven-room, ostentatious Grand Apartment, and the highly-curated, maze-like gardens (replete with an Orangerie); it’s hard not to imagine what life could have been like had you and your beau been French heirs.', 'https://www.jetsetter.com/wp-content/uploads/sites/7/2018/04/ccvl7VbN-1380x1035.jpeg', 1, 4),
('Pont des Arts (Love Lock Bridge)', null, null, 'Pont des Arts, 75006 Paris, France', 'Pont des Arts has been a popular spot for Parisian rendezvous since 2008—when committed couples first began affixing engraved locks on the bridge’s railings, dropping their keys into the Seine below. Though this practice is now banned, visitors are still encouraged to drop by and take photos as they enjoy the view and each other’s company.','https://dsx.weather.com//util/image/w/a0ed464c-9977-48d4-bfd8-5e69520ec3c7.jpg?v=at&w=485&h=273&api=7db9fe61-7414-47b5-9871-e17d87b8b6a0', 1, 4),
('Musée Yves Saint Laurent', '+33 (0)1 44 31 64 00', 'https://museeyslparis.com/en/', '5 avenue Marceau
75116 Paris - France',  'The couture house at 5 Avenue Marceau, where Yves Saint Laurent worked for almost 30 years, presents the world class couturiers designs in various rooms, each showcasing his signature style. From his designs from the Dior years to the most famous looks from YSL. This is a must see for any fashion connoisseur.', 'https://media.timeout.com/images/104028834/630/472/image.jpg', 1, 4), 
('Rue du Faubourg Saint-Honoré', null, null, 'Rue du Faubourg Saint-Honoré, Paris, France', 'If retail therapy will help you get your fashion fix, then head to Rue du Fauburg Saint-Honoré. It’s the perfect place to wander and enjoy some high fashion – even if it’s just to look! It’s known as one of the best shopping streets in the world. The narrow Parisian street is home to fashion houses large and small, from Chloe to Givenchy.', 'https://cdn-image.departures.com/sites/default/files/styles/responsive_900x600/public/20120304-ss-worlds-top-shopping-streest-rue-du-faubourg-saint-honore-paris.jpg?itok=Jj9L5wjV', 1, 3),
('Musée des Arts Décoratifs', '+33 (0)1 44 55 57 50', 'https://madparis.fr/en/', '107-111, rue de Rivoli, 75001 Paris, France', 'The collection of the Museum of Decorative Arts, one of the most important in the world, presents, from the Middle Ages to the present day, an unequaled panorama of the history of furniture, glass, ceramics, goldsmith''s work, jewelery, design, textiles and fashion, graphics and advertising.', 'https://en.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/musee-des-arts-decoratifs-630x405-c-otcp-marc-bertrand-i-159-30/25257-1-fre-FR/Musee-des-Arts-decoratifs-630x405-C-OTCP-Marc-Bertrand-I-159-30.jpg', 1, 4)




