INSERT INTO activities(name, phone, website_url, address, description, image_url, city_id, category_id)
VALUES
('Fouquet''s', '+33(0)1 40 69 60 50', 'https://www.hotelsbarriere.com/fr/paris/le-fouquets/restaurants-et-bars/fouquets.html',  '99, avenue des Champs-Elysées, 75 008 Paris, France', 'Since 1899, Fouquet''s brasserie has embodied the Parisian spirit, brilliant and festive. Ideally located at the corner of the Champs-Elysées and Avenue George V, the famous brasserie houses a classic Parisian brasserie decor, and proudly displays its eternal link with the arts and cinema. This mythical setting opens onto two magnificent terraces, on the Champs-Elysées and Avenue George V.', 'https://res.cloudinary.com/tf-lab/image/upload/restaurant/f2fa383d-eee5-452f-80c4-af21fb6d433a/714dfd3d-6b3b-418d-803e-d40a442d0339.jpg', 1, 1),
('Le Jules Verne', '+33(0)1 83 77 34 34', 'https://www.restaurants-toureiffel.com/en/jules-verne-restaurant.html', '2nd floor of the Eiffel Tower, Avenue Gustave Eiffel, 75007 Paris, France', 'Le Jules Verne is a dizzying ascent of the Eiffel Tower to enjoy the most beautiful view of Paris. Three dining rooms give three exceptional viewpoints: Quai Branly, Trocadéro and Champ de Mars.', 'https://bonjourparis.com/wp-content/uploads/2020/02/Interiors-LJV_Trocadero_02_Copyright-Marie-Line-Sina-min-min.jpg', 1, 1),
('Jòia', '+33(0)1 40 20 06 06', 'https://www.joiahelenedarroze.com/en/', '39 rue des Jeuneurs, 75002 Paris,France', 'On two floors, Joia boasts a casual and warm elegance. On the plate, grandmothers'' recipes are combined with London, New York and Italian-inspired delicacies. A few friends crush their own guacamole in a mortar while waiting for the next step, while two lovers enjoy a cogote of hake from Saint-Jean de Luz, roasted in a Spanish style with a chimichurri sauce.', 'https://www.joiahelenedarroze.com/_files/_media/27/Photos/Helene-Darroze-Joia.jpg', 1, 1),
('Aux Bons Crus', '+33(0)1 45 67 21 13', 'http://www.auxbonscrus.fr/index_en.html', '54 rue Godefroy Cavaignac, 5011 Paris, France', 'Welcome to Aux Bons Crus, the true Parisian Bistro, the one you dreamt of. Sit down, relax and enjoy our family recipes from the region of Lyon, the land of famous chef Paul Bocuse! The menu offers simple yet delicious dishes made with fresh ingredients, every day.', 'http://www.auxbonscrus.fr/img2/IMG_4157.jpg', 1, 1),
('Le Mur Des Je t''aime (The Wall of Love)', null, 'http://www.lesjetaime.com/', 'Square Jehan Rictus, Place des Abbesses, 75018 Paris, France', 'Tucked away in Montmartre’s petite Jehan Rictus garden square, Le Mur Des Je t’aime attracts its fair share of lovebirds each day. Artists Fédéric Baron and Claire Kito created the mural in 2000, adorning it with hundreds of variations of Je t’aime (I Love You) in 250 different languages and dialects.', 'https://12in12traveler.com/storage/2017/09/I-love-you-wall.jpg', 1, 4),
('La Tour Eiffel (The Eiffel Tower)', '+33 (0)8 92 70 12 39', 'https://www.toureiffel.paris/en', 'Champ de Mars, 5 Avenue Anatole France, 75007 Paris, France', 'The Eiffel Tower, La Tour Eiffel in French, was the main exhibit of the Paris Exposition — or World''s Fair — of 1889. It was constructed to commemorate the centennial of the French Revolution and to demonstrate France''s industrial prowess to the world.', 'https://cdn.mos.cms.futurecdn.net/z3rNHS9Y6PV6vbhH8w83Yn-1024-80.jpg.webp', 1, 4),
('Château de Versailles (Palace of Versailles', '+ 33(0)1 30 83 78 00', 'http://en.chateauversailles.fr/', 'Place d''Armes, 78000 Versailles, France', 'About an hour outside of the city, Palace de Versailles—once the home of infamous Marie Antoinette—is a day trip worth making. Wander through the chandelier-strung Hall of Mirrors, the King’s seven-room, ostentatious Grand Apartment, and the highly-curated, maze-like gardens (replete with an Orangerie); it’s hard not to imagine what life could have been like had you and your beau been French heirs.', 'https://www.jetsetter.com/wp-content/uploads/sites/7/2018/04/ccvl7VbN-1380x1035.jpeg', 1, 4),
('Pont des Arts (Love Lock Bridge)', null, null, 'Pont des Arts, 75006 Paris, France', 'Pont des Arts has been a popular spot for Parisian rendezvous since 2008—when committed couples first began affixing engraved locks on the bridge’s railings, dropping their keys into the Seine below. Though this practice is now banned, visitors are still encouraged to drop by and take photos as they enjoy the view and each other’s company.','https://dsx.weather.com//util/image/w/a0ed464c-9977-48d4-bfd8-5e69520ec3c7.jpg?v=at&w=485&h=273&api=7db9fe61-7414-47b5-9871-e17d87b8b6a0', 1, 4),
('Musée Yves Saint Laurent', '+33 (0)1 44 31 64 00', 'https://museeyslparis.com/en/', '5 avenue Marceau
75116 Paris - France',  'The couture house at 5 Avenue Marceau, where Yves Saint Laurent worked for almost 30 years, presents the world class couturiers designs in various rooms, each showcasing his signature style. From his designs from the Dior years to the most famous looks from YSL. This is a must see for any fashion connoisseur.', 'https://media.timeout.com/images/104028834/630/472/image.jpg', 1, 4), 
('Rue du Faubourg Saint-Honoré', null, null, 'Rue du Faubourg Saint-Honoré, Paris, France', 'If retail therapy will help you get your fashion fix, then head to Rue du Fauburg Saint-Honoré. It’s the perfect place to wander and enjoy some high fashion – even if it’s just to look! It’s known as one of the best shopping streets in the world. The narrow Parisian street is home to fashion houses large and small, from Chloe to Givenchy.', 'https://cdn-image.departures.com/sites/default/files/styles/responsive_900x600/public/20120304-ss-worlds-top-shopping-streest-rue-du-faubourg-saint-honore-paris.jpg?itok=Jj9L5wjV', 1, 3),
('Musée des Arts Décoratifs', '+33 (0)1 44 55 57 50', 'https://madparis.fr/en/', '107-111, rue de Rivoli, 75001 Paris, France', 'The collection of the Museum of Decorative Arts, one of the most important in the world, presents, from the Middle Ages to the present day, an unequaled panorama of the history of furniture, glass, ceramics, goldsmith''s work, jewelery, design, textiles and fashion, graphics and advertising.', 'https://en.parisinfo.com/var/otcp/sites/images/media/1.-photos/02.-sites-culturels-630-x-405/musee-des-arts-decoratifs-630x405-c-otcp-marc-bertrand-i-159-30/25257-1-fre-FR/Musee-des-Arts-decoratifs-630x405-C-OTCP-Marc-Bertrand-I-159-30.jpg', 1, 4),
('Bisou', '+33 1 40 27 82 85', 'https://en.bar-bisou.fr/', '15 Boulevard du Temple, 75003 Paris, France', 'There''s no menu at this small bar off the boulevard in the Haute Marais. It''s all about what you like—and what the bartender feels like making. You discuss your liquor and flavors of choice with whomever''s shaking things up, and voilà! A mysterious cocktail will appear. Considering its small size and romantic vibe, it''s best for a date or a small group of friends, largely of the Instagram generation (the bar is done up in Millennial Pink).', 'https://www.materrazza.com/sites/default/files/NB__20190214_079-2.jpg', 1, 2),
('Bar Hemingway', '+33 1 43 16 33 74', 'https://www.ritzparis.com/en-GB/fine-dining-paris/bar-hemingway', '15 Place Vendôme, 75001 Paris, France', 'The world’s most famous (and smallest) Bar owes its name to the journalist and writer who was a regular. With Colin Field, the twice-named "Best Head Barman in the World", the legend lives on... Every evening, many fans and followers strive to land one of the 25 seats in this iconic Bar with the aura of a Members'' Club. Tufted leather armchairs, a library, photos and an old-fashioned typewriter, the absence of music to encourage conversations... the alchemy of the place is indescribably special: just one visit and you’ll understand.', 'https://www.ritzparis.com/sites/default/files/styles/1440x748/public/images/card_page/slideshow/ritz-paris-hotel-bar-hemingway-1_0.jpg?itok=7iQw-6tZ', 1, 2),
('Le Comptoir Géneral', '+33 1 44 88 24 48', 'https://www.lecomptoirgeneral.com/#firstPage', '80 Quai de Jemmapes, 75010 Paris, France', 'Ask owner Étienne Tron what this Canal Saint-Martin dive is all about, and he is likely to call Le Comptoir Général a "museum." Indeed, it''s built in a barn directly on the Canal, and it''s filled with all sorts of antique armchairs, vintage posters and lamps, and every sort of bric-a-brac you can imagine. There''s a North African bent to the cocktail menu, which includes bright, often tropical, drinks. And if you''re a beer enthusiast, there''s a great selection of obscure IPAs and organic brews.', 'https://media.cntraveler.com/photos/5cf979ee6640e76998e1d199/16:9/w_2560%2Cc_limit/Le-Comptoir-Ge%2525CC%252581neral_2019_Comptoir-Ge%2525CC%252581ne%2525CC%252581ral-4-%2525C2%2525A9Matthieu-Salvaing.jpg', 1, 2),
('CopperBay', null, 'http://copperbay.fr/', '5 Rue Bouchardon, 75010 Paris, France', 'The marine-inspired decor makes this unpretentious spot feel like vacation: shades of blue and green, ropes draped from the ceiling (in between the requisite Edison bulbs), and wooden ores hung as wall art. The menu, which changes seasonally, comes in two forms: handwritten in script on a giant paper scroll behind the bar and via a deck of cards that explain the components of each cocktail via a hefty description and a colorful pie chart. While they can make anything you want, specialities are worth trying like the Petit Artichaut made with a nut butter-infused whisky, bitters, Pedro Ximenez sherry, and Guinness. They also do a selection of beers (from local Parisian brewery Demory), ciders from Appie, and natural white or red wine by the glass or bottle.','https://media.cntraveler.com/photos/5a80a8577211e1293261ce4a/16:9/w_2560%2Cc_limit/Copper-Bay__2018_COPPERBAY-3-%2525C2%2525A9I.Mathie-HD.jpg', 1, 2),
('Gravity Bar', '+33 6 98 54 92 49', 'https://m.facebook.com/gravitybar/', '44 Rue des Vinaigriers, 75010 Paris, France', 'True to its name, you''ll feel as if you bolted into outer space upon walking into this spot near Canal Saint-Martin. The bar itself is your space-ship, with concrete counters and curved slats of plywood that extend over the space via the ceiling. They like to shake things up here—both with classics or their own creations. But while they''ve got around a dozen quirky cocktails to keep you sated, their wine and beer selection is top-notch, too.', 'https://media.cntraveler.com/photos/5a80a85d52e7b4436ff64db7/16:9/w_2560%2Cc_limit/Gravity_JB-Lemal_2018_4---copie.jpg', 1, 2),
('Boulevard Haussmann and the Grands Boulevards', null, null, 'Boulevard Haussmann; Place de la Madeleine', 'The old Parisian department stores are famous for being worlds unto themselves. Galeries Lafayette and Printemps department stores dominate Boulevard Haussmann with real Belle Epoque grandeur, concentrating top designer collections for men and women, gourmet food shopping, home design, jewelry, and even hardware into a labyrinth of consumer delights. In the winter months, of course, these "grands magasins" are decked out with lights and elaborate decorations for the holiday season, so don''t miss checking them out then.', 'http://www.thetripblogger.com/wp-content/uploads/2016/05/Boulevard-Haussmann.jpg', 1, 3),
('Avenue Montaigne and the Champs-Elysées', null, null, 'Avenue Montaigne; Avenue des Champs-Elysées', 'Avenue Montaigne and Avenue des Champs-Elysées form one of the city''s most coveted fashion junctures. Avenue Montaigne is fast outstripping Saint Honoré in the arena of chic-cachet, with legendary designers like Chanel and Dior lining the street with flagship boutiques. The Champs-Elysées, for its part, features luxury names (Louis Vuitton) while also being a major spot for shopping in trendy global chains like Zara. Meanwhile, to keep the kids happy, the Disney Store dominates the "Champs" with fun window displays and enough toys to colonize the moon.', 'https://cdn.lifestyleasia.com/wp-content/uploads/2019/07/16172315/Dior-Storefront-CHAMPSELYS.jpg', 1, 3),
('Le Marais', null, null, 'Rue des Francs-Bourgeois, Place des Vosges, Rue de Turenne, Rue des Rosiers', 'The historic Marais quarter is prime stomping ground for shoppers with an eye for the unique and finely-crafted, not to mention antique and fine art lovers. Try antiques or fine-arts shopping on the Place des Vosges, jewelry, fragrance, and cosmetics shopping at boutiques like Diptyque and MAC on Rue des Francs-Bourgeois, or plunder fashionable but accessible chains such as COS on Rue des Rosiers.', 'https://img.theculturetrip.com/1440x/smart/wp-content/uploads/2019/01/hb05pd.jpg', 1, 3),
('Saint-Germain-des-Prés', null, null, 'Blvd. St.-Germain, Rue St. André-des-Arts, Rue de Sèvres', 'Once synonymous with the famous intellectuals who haunted local cafés, St.-Germain-des-Prés has acquired several shades of chic and is now a preferred spot of BCBG''s (yuppies). Sonia Rykiel and Paco Rabanne have boutiques here: Try Rue Saint-Andre des Arts for rare books, unique regional gifts, and vintage threads. Meanwhile, for local department store shopping, the Bon Marché is the consummate left-bank address for classic chic. If you''re a foodie or are in search of gourmet goods to take home, make sure to have a whirl through the enormoys food hall there, too.', 'https://headtopics.com/images/2020/8/22/vogueparis/belgium-moves-to-bon-marche-for-an-exclusive-exhibition-1296916315261865986.webp', 1, 3);





